Repository master-csmi/2024-m1-vegetation, pull requests merged in 2024-03, with the labels that each got.

#33 update .bib
  references.bib
  report.tex
Labels: documentation

#47 4 write initial report
  README.adoc
  README.md
  references.bib
  report.tex
Labels: documentation

#51 4 write initial report
  images/NY_mesh.png
  images/roadmap_v0.png
  images/roadmap_v1.png
  images/roadmap_v2.png
  images/tree_mesh.png
  references.bib
  report.tex
  script_v0.txt
Labels: report

#55 update CMake for macOS usage #54
  CMakeLists.txt
Labels: bug

#59 Presentation improvement
  .github/workflows/compile.yml
  CMakeLists.txt
  CMakePresets.json
  images/LOD0.png
  images/LOD1.png
  images/LOD2.png
  images/TreeShade.png
  images/cgal_logo.png
  images/feelpp.png
  images/meshlab_logo.png
  intro.tex
  output/arbre1_20_600.off
  presentation_v0.tex
  references.bib
  report.tex
Labels: presentation

#60 24 v0 feedback
  .gitignore
  images/OvAPI_logo.png
  images/alphaWbike.png
  images/osm_logo.png
  references.bib
  report.tex
Labels: enhancement
